name: Update Countdown

on:
  schedule:
    - cron: "0 0 * * *"   # Runs every day at midnight UTC
  workflow_dispatch:       # Allow manual run

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Update Countdown Badge
        run: |
          python3 <<EOF
          from datetime import datetime

          event_date = datetime(2025, 8, 23)
          today = datetime.utcnow().date()
          days_left = (event_date.date() - today).days

          readme = "README.md"
          with open(readme, "r") as f:
              content = f.read()

          import re
          new_badge = f"https://img.shields.io/badge/Countdown-{days_left}%20Days%20to%20Go-ff69b4?style=for-the-badge"
          content = re.sub(r"https://img.shields.io/badge/Countdown-.*?-ff69b4\?style=for-the-badge", new_badge, content)

          with open(readme, "w") as f:
              f.write(content)
          EOF

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Auto-update countdown badge"
          git push
